ALTER TABLE BUSINESS DROP FOREIGN KEY FK_BUSINESS_BUSINESSHOURS_ID
ALTER TABLE SERVICE DROP FOREIGN KEY FK_SERVICE_BUSINESS_EMAIL
ALTER TABLE BUSINESSHOURS DROP FOREIGN KEY FK_BUSINESSHOURS_BUSINESS_EMAIL
ALTER TABLE CLIENT DROP FOREIGN KEY FK_CLIENT_REVIEW_ID
ALTER TABLE PROMOTIONS DROP FOREIGN KEY FK_PROMOTIONS_BUSINESS_EMAIL
ALTER TABLE REVIEW DROP FOREIGN KEY FK_REVIEW_BUSINESS_EMAIL
ALTER TABLE REVIEW DROP FOREIGN KEY FK_REVIEW_CLIENT_EMAIL
ALTER TABLE BUSINESS_EMPLOYEES DROP FOREIGN KEY FK_BUSINESS_EMPLOYEES_employeesList_EMPID
ALTER TABLE BUSINESS_EMPLOYEES DROP FOREIGN KEY FK_BUSINESS_EMPLOYEES_Business_EMAIL
ALTER TABLE BUSINESS_PROMOTIONS DROP FOREIGN KEY FK_BUSINESS_PROMOTIONS_Business_EMAIL
ALTER TABLE BUSINESS_PROMOTIONS DROP FOREIGN KEY FK_BUSINESS_PROMOTIONS_promotionList_PROMOID
ALTER TABLE BUSINESS_REVIEW DROP FOREIGN KEY FK_BUSINESS_REVIEW_Business_EMAIL
ALTER TABLE BUSINESS_REVIEW DROP FOREIGN KEY FK_BUSINESS_REVIEW_reviewList_ID
ALTER TABLE BUSINESS_SERVICE DROP FOREIGN KEY FK_BUSINESS_SERVICE_Business_EMAIL
ALTER TABLE BUSINESS_SERVICE DROP FOREIGN KEY FK_BUSINESS_SERVICE_serviceList_SERVICEID
DROP TABLE BUSINESS
DROP TABLE SERVICE
DROP TABLE BUSINESSHOURS
DROP TABLE CLIENT
DROP TABLE EMPLOYEES
DROP TABLE PROMOTIONS
DROP TABLE REVIEW
DROP TABLE BUSINESS_EMPLOYEES
DROP TABLE BUSINESS_PROMOTIONS
DROP TABLE BUSINESS_REVIEW
DROP TABLE BUSINESS_SERVICE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
